### ISSUE TITLE
Issue with some modules

### ISSUE THREAD

**Issue by jonaths** [bitsoex/bitso-py#3]
Im trying to use some examples and getting issues with websocket and ordertree modules. I tried the basic examples and they work well. I properly installed bitso-py using python setup.py install. This is the error that appeared when running the code at https://github.com/bitsoex/bitso-py/blob/master/examples/livebookexample.py. Any idea about whats going on? Thanks. 

Traceback (most recent call last):
  File "livebookexample.py", line 32, in <module>
    import bitso
  File "/usr/local/lib/python2.7/dist-packages/bitso_py-3.0.0-py2.7.egg/bitso/__init__.py", line 54, in <module>
    from .bitsows import (Listener, Client)
  File "/usr/local/lib/python2.7/dist-packages/bitso_py-3.0.0-py2.7.egg/bitso/bitsows.py", line 27, in <module>
    import websocket
  File "/media/jonathan/Data/Bitso/Examples/websocket.py", line 34, in <module>
    from ordertree import OrderTree
ImportError: No module named ordertree

**Comment by mariorz** [comment]
Hi Jonaths, the ordertree module is included in the examples: https://github.com/bitsoex/bitso-py/blob/master/examples/ordertree.py

Not sure what is going on with your setup though, that websocket.py file you are trying to import is not part of the example directory, it should be importing the websocket-client module https://github.com/websocket-client/websocket-client that is marked as one of the requirements. Perhaps you are getting mixed up with a previous bitso-py version?
